"""Load JSON Schema generated by @flatwalk/contract. Do not define FlatModel here.

Expected files (written by `npm run schema:generate -w @flatwalk/contract`):
  modules/contract/schemas/Patch.schema.json
  modules/contract/schemas/FlatModel.schema.json

Override the directory with FLATWALK_CONTRACT_SCHEMAS. Missing files mean
task 0.2 artifacts are not published yet; the stub still runs without them.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

_SCHEMA_NAMES = ("Patch", "FlatModel", "ValidationReport", "RevisionContext")


def contract_schema_dir() -> Path:
    override = os.environ.get("FLATWALK_CONTRACT_SCHEMAS")
    if override:
        return Path(override)
    here = Path(__file__).resolve()
    for parent in here.parents:
        candidate = parent / "modules" / "contract" / "schemas"
        if candidate.is_dir() or (parent / "modules" / "contract" / "package.json").is_file():
            return candidate
    return here.parent / "missing-contract-schemas"


def load_json_schema(name: str) -> dict[str, Any] | None:
    path = contract_schema_dir() / f"{name}.schema.json"
    if not path.is_file():
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} is not a JSON object")
    return payload


def schema_availability() -> dict[str, bool]:
    return {name: load_json_schema(name) is not None for name in _SCHEMA_NAMES}


def validate_patch(patch: dict[str, Any]) -> list[str]:
    """Validate a non-null patch against Contract JSON Schema when present."""
    schema = load_json_schema("Patch")
    if schema is None:
        return ["contract-schema-unavailable: Patch.schema.json"]
    from jsonschema import Draft202012Validator

    return [
        f"{'/'.join(str(p) for p in error.absolute_path)}: {error.message}"
        if error.absolute_path
        else error.message
        for error in Draft202012Validator(schema).iter_errors(patch)
    ]
